image: node:latest

services:
  - redis:latest

variables:
  REDIS_URL: redis://redis:6379
  REDIS_PORT: 6379

stages:
  - install
  - test
  - build

install:
  stage: install
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
  script:
    - yarn install --frozen-lockfile
  only:
    changes:
      - yarn.lock

unit:
  stage: test
  needs: ["install"]
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn test:unit

acceptance:
  stage: test
  needs: ["install"]
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn test:acceptance

build:
  stage: build
  needs: ["install"]
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn build
  artifacts:
    paths:
      - dist

lint:
  stage: test
  needs: ["install"]
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn lint
