image: node:latest

services:
  - redis:latest

variables:
  REDIS_URL: redis://redis:6379
  REDIS_PORT: 6379

stages:
  - test
  - deploy

unit:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn
    - yarn test:unit --reporters=default --reporters=jest-junit
  artifacts:
    when: always
    reports:
      junit:
        - junit.xml

acceptance:
  stage: test
  cache:
    - key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
      paths:
        - node_modules/
      policy: pull
    - paths:
        - coverage/
  script:
    - yarn
    - yarn test:acceptance --reporters=default --reporters=jest-junit
  artifacts:
    when: always
    paths:
      - coverage/
    reports:
      junit:
        - junit.xml
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

build:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull-push
  script:
    - yarn 
    - yarn build
  artifacts:
    paths:
      - dist

lint:
  stage: test
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn
    - yarn lint

deploy:
  stage: deploy
  cache:
    key: $CI_COMMIT_REF_SLUG-$CI_PROJECT_DIR
    paths:
      - node_modules/
    policy: pull
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=cis2022-arena --api-key=$HEROKU_API_KEY_DEV
  only:
    - master

pages:
  stage: deploy
  dependencies:
    - acceptance
  script:
    - mkdir .public
    - cp -r coverage/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
